In [59]:
import torch
import numpy as np
from IPython.display import Image
from IPython.core.display import HTML 

## What is PyTorch?
- A python library to operate on Tensors as a replacement over Numpy 
- A Deep Learning library that provides easy of use and flexibility for researchers and practitioners

## 1. Create new tensors

### 1.1 Empty Tensor

In [4]:
torch.empty(5, 4) #the values are close to zero

tensor([[2.9159e+38, 4.5615e-41, 2.9159e+38, 4.5615e-41],
        [0.0000e+00, 0.0000e+00, 5.9819e+19, 4.5615e-41],
        [0.0000e+00, 0.0000e+00, 4.9615e+19, 4.5615e-41],
        [0.0000e+00, 0.0000e+00,        nan, 3.3460e-12],
        [1.4013e-45, 0.0000e+00, 4.9518e+28, 7.9463e+08]])

### 1.2 Random Tensor

In [11]:
torch.randn(1, 4) # generates random values

tensor([[ 0.2900, -1.8238,  0.0839, -0.5769]])

### 1.3 Zero Tensor

In [10]:
torch.zeros(3, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

### 1.4 From a list

In [19]:
x = torch.tensor([[2.3, 4], [1.2, -0.3]])

In [20]:
x

tensor([[ 2.3000,  4.0000],
        [ 1.2000, -0.3000]])

### 1.5 From an existing tensor

In [58]:
# rand - random positive
# randn - random positive and negative
torch.randn_like(x)
# torch.ones_like(x)
# torch.zeros_like(x)

tensor([[-1.7953, -0.1728],
        [-0.2738, -0.2925]])

### 1.6 From numpy array

In [61]:
n = np.array([[1, 2], [0.3, -1.2]])

torch.from_numpy(n)

tensor([[ 1.0000,  2.0000],
        [ 0.3000, -1.2000]], dtype=torch.float64)

## 2. Slicing Tensors

If you are already familiar with numpy, you can skip this section

In [72]:
x = torch.randn(3, 4, 5)

In [73]:
x

tensor([[[ 1.1930, -0.3808, -0.8907, -1.7130,  0.1500],
         [-0.3511, -1.1963,  0.3327, -1.1608, -0.4557],
         [ 1.9224, -0.9547,  0.5528,  2.0848,  0.9394],
         [-0.7937,  0.4034, -0.3482, -0.2343,  0.3509]],

        [[-0.6110, -0.4482, -1.2750, -0.4663,  0.2621],
         [ 0.2856, -1.0831,  0.9597,  0.5971, -1.4496],
         [-0.7251,  0.8108, -0.1436, -0.5671,  0.5719],
         [-0.8660, -1.1224,  0.2852,  0.2463, -0.9215]],

        [[-0.2689,  0.7704,  1.1415,  0.7557, -0.4813],
         [-0.2387,  2.9216, -0.1847,  0.9027,  1.1900],
         [ 1.5327,  0.3733, -0.9201,  0.6989,  0.0082],
         [ 0.1920,  1.0249,  0.6636,  1.1873,  0.1856]]])

### 2.1 Know the size

In [74]:
x.size()

torch.Size([3, 4, 5])

### 2.2 Access with numpy style slicing

In [75]:
# identify the dimension you want to access [3, 4, 5]

# if you want all elements from first dimension, 2nd element from 2nd dimension, all elements from 3rd dimension
x[:, 1, :]

tensor([[-0.3511, -1.1963,  0.3327, -1.1608, -0.4557],
        [ 0.2856, -1.0831,  0.9597,  0.5971, -1.4496],
        [-0.2387,  2.9216, -0.1847,  0.9027,  1.1900]])

In [76]:
# if you want 1st element from first dimension, 2nd element from 2nd dimension, all elements from 3rd dimension
x[0, 1, :]

tensor([-0.3511, -1.1963,  0.3327, -1.1608, -0.4557])

In [77]:
# if you want first two elements from first dimension, 
# first 3 elements from 2nd dimension and 
# only 4th element from 3rd dimension
x[:2, :3, 3]

tensor([[-1.7130, -1.1608,  2.0848],
        [-0.4663,  0.5971, -0.5671]])

## 3. Tensor Transform

### 3.1 Resize

In [78]:
x.size()

torch.Size([3, 4, 5])

In [79]:
x.view(12, 5)
# x.view(3, 20)
# x.view(4, 15)
# x.view(60)

tensor([[ 1.1930, -0.3808, -0.8907, -1.7130,  0.1500],
        [-0.3511, -1.1963,  0.3327, -1.1608, -0.4557],
        [ 1.9224, -0.9547,  0.5528,  2.0848,  0.9394],
        [-0.7937,  0.4034, -0.3482, -0.2343,  0.3509],
        [-0.6110, -0.4482, -1.2750, -0.4663,  0.2621],
        [ 0.2856, -1.0831,  0.9597,  0.5971, -1.4496],
        [-0.7251,  0.8108, -0.1436, -0.5671,  0.5719],
        [-0.8660, -1.1224,  0.2852,  0.2463, -0.9215],
        [-0.2689,  0.7704,  1.1415,  0.7557, -0.4813],
        [-0.2387,  2.9216, -0.1847,  0.9027,  1.1900],
        [ 1.5327,  0.3733, -0.9201,  0.6989,  0.0082],
        [ 0.1920,  1.0249,  0.6636,  1.1873,  0.1856]])

### 3.1 Add a new dimension

In [86]:
# only one dimension can be added
x.view(3, 4, -1, 5).size()
# x.view(3, 4, 5, -1).size()
# x.view(-1, 3, 4, 5).size()

torch.Size([3, 4, 1, 5])

## 4. Operations

### 4.1 Addition

In [88]:
x = torch.rand(3, 4)
y = torch.rand(3, 4)

In [91]:
x + y

tensor([[1.3400, 0.6052, 0.7668, 1.6158],
        [0.7968, 0.2113, 1.1010, 0.6425],
        [1.0882, 0.6075, 0.8668, 1.0942]])

In [92]:
x.add(y)

tensor([[1.3400, 0.6052, 0.7668, 1.6158],
        [0.7968, 0.2113, 1.1010, 0.6425],
        [1.0882, 0.6075, 0.8668, 1.0942]])

In [93]:
# inplace
x.add_(y)

tensor([[1.3400, 0.6052, 0.7668, 1.6158],
        [0.7968, 0.2113, 1.1010, 0.6425],
        [1.0882, 0.6075, 0.8668, 1.0942]])

In [94]:
x

tensor([[1.3400, 0.6052, 0.7668, 1.6158],
        [0.7968, 0.2113, 1.1010, 0.6425],
        [1.0882, 0.6075, 0.8668, 1.0942]])

In [95]:
torch.add(x, y)

tensor([[1.9126, 0.8663, 0.9828, 2.3942],
        [1.0305, 0.3241, 1.7627, 1.1404],
        [1.9983, 0.9439, 1.1492, 1.5844]])

In [98]:
# torch.mul(x, y)
# torch.div(x, y)
torch.sub(x, y)

tensor([[0.7674, 0.3441, 0.5507, 0.8373],
        [0.5630, 0.0985, 0.4394, 0.1447],
        [0.1781, 0.2711, 0.5844, 0.6040]])

### More such operations can be found here https://pytorch.org/docs/stable/torch.html

## 5. Autograd

- Automatic differentiation on all tensor operations provided as part of the library
- Operates on tensor
- When creating a tensor set .requires_grad to True

\begin{align}
x & = \begin{bmatrix}{x}_1\\
{x}_2 \\ 
..
\\
{x}_n
\end{bmatrix} \\ \\
f(x) & = \sum_{n}  3 * (x+2)^2 \\ \\
\frac{d f}{dx} & = \begin{bmatrix}
6({x}_1 + 2) \\
6({x}_2 + 2) \\
.. \\
6({x}_n + 2)
\end{bmatrix}\\
\end{align}

### 5.1 Set requires_grad as True

In [109]:
x = torch.ones(10, requires_grad=True)
x

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.], requires_grad=True)

### 5.2 Perform Operations on the tensor

In [110]:
y = x+2
z = 3 * y * y
out = sum(z)

In [111]:
out

tensor(270., grad_fn=<AddBackward0>)

### 5.3 Perform backward operation to calculate gradients

In [112]:
out.backward()

### 5.4 Check gradients

In [113]:
x.grad

tensor([18., 18., 18., 18., 18., 18., 18., 18., 18., 18.])

### 5.5 Stop tracking operations

In [ ]:
x.detach()
# with torch.no_grad():
#      perform operations

### 5.6 Convert to Scalar

In [122]:
y # needs a scalar to compute gradients

tensor([3., 3., 3., 3., 3., 3., 3., 3., 3., 3.], grad_fn=<AddBackward0>)

In [131]:
Image(url= "../Jacobian.jpg")

In [133]:
Image(url = "../Jacobian-vector.jpg")

In [119]:
y.backward(torch.ones(10))